{
  "openapi": "3.1.0",
  "info": {
    "title": "DeepAha Ops Gateway",
    "version": "1.1.0"
  },
  "paths": {
    "/health": {
      "get": {
        "summary": "Health",
        "operationId": "health_health_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        }
      }
    },
    "/v1/capabilities": {
      "get": {
        "summary": "Capabilities",
        "operationId": "capabilities_v1_capabilities_get",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/status": {
      "get": {
        "summary": "Status",
        "operationId": "status_v1_status_get",
        "parameters": [
          {
            "name": "environment",
            "in": "query",
            "required": true,
            "schema": {
              "enum": [
                "staging",
                "production"
              ],
              "type": "string",
              "title": "Environment"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/logs": {
      "get": {
        "summary": "Logs",
        "operationId": "logs_v1_logs_get",
        "parameters": [
          {
            "name": "environment",
            "in": "query",
            "required": true,
            "schema": {
              "enum": [
                "staging",
                "production"
              ],
              "type": "string",
              "title": "Environment"
            }
          },
          {
            "name": "service",
            "in": "query",
            "required": true,
            "schema": {
              "enum": [
                "api",
                "worker"
              ],
              "type": "string",
              "title": "Service"
            }
          },
          {
            "name": "lines",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 500,
              "minimum": 20,
              "default": 100,
              "title": "Lines"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/gateway/logs": {
      "get": {
        "summary": "Gateway Logs",
        "operationId": "gateway_logs_v1_gateway_logs_get",
        "parameters": [
          {
            "name": "lines",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 500,
              "minimum": 20,
              "default": 100,
              "title": "Lines"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/operations": {
      "get": {
        "summary": "Operations",
        "operationId": "operations_v1_operations_get",
        "parameters": [
          {
            "name": "environment",
            "in": "query",
            "required": true,
            "schema": {
              "enum": [
                "staging",
                "production"
              ],
              "type": "string",
              "title": "Environment"
            }
          },
          {
            "name": "limit",
            "in": "query",
            "required": false,
            "schema": {
              "type": "integer",
              "maximum": 100,
              "minimum": 1,
              "default": 20,
              "title": "Limit"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/operations/{operation_id}": {
      "get": {
        "summary": "Operation",
        "operationId": "operation_v1_operations__operation_id__get",
        "parameters": [
          {
            "name": "operation_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "title": "Operation Id"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/deploy": {
      "post": {
        "summary": "Deploy",
        "operationId": "deploy_v1_deploy_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DeployRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "202": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-openai-isConsequential": true,
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/backup": {
      "post": {
        "summary": "Backup",
        "operationId": "backup_v1_backup_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/BackupRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "202": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-openai-isConsequential": true,
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/rollback": {
      "post": {
        "summary": "Rollback",
        "operationId": "rollback_v1_rollback_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RollbackRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "202": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-openai-isConsequential": true,
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/v1/restart": {
      "post": {
        "summary": "Restart",
        "operationId": "restart_v1_restart_post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RestartRequest"
              }
            }
          },
          "required": true
        },
        "responses": {
          "202": {
            "description": "Successful Response",
            "content": {
              "application/json": {
                "schema": {}
              }
            }
          },
          "422": {
            "description": "Validation Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPValidationError"
                }
              }
            }
          }
        },
        "x-openai-isConsequential": true,
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "BackupRequest": {
        "properties": {
          "environment": {
            "type": "string",
            "enum": [
              "staging",
              "production"
            ],
            "title": "Environment"
          },
          "expected_current": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}$",
            "title": "Expected Current"
          },
          "idempotency_key": {
            "type": "string",
            "pattern": "^[A-Za-z0-9._:-]{8,128}$",
            "title": "Idempotency Key"
          },
          "approval_id": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^[0-9a-f]{32}$"
              },
              {
                "type": "null"
              }
            ],
            "title": "Approval Id"
          }
        },
        "additionalProperties": false,
        "type": "object",
        "required": [
          "environment",
          "expected_current",
          "idempotency_key"
        ],
        "title": "BackupRequest"
      },
      "DeployRequest": {
        "properties": {
          "environment": {
            "type": "string",
            "enum": [
              "staging",
              "production"
            ],
            "title": "Environment"
          },
          "expected_current": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}$",
            "title": "Expected Current"
          },
          "idempotency_key": {
            "type": "string",
            "pattern": "^[A-Za-z0-9._:-]{8,128}$",
            "title": "Idempotency Key"
          },
          "approval_id": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^[0-9a-f]{32}$"
              },
              {
                "type": "null"
              }
            ],
            "title": "Approval Id"
          },
          "commit_sha": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}$",
            "title": "Commit Sha"
          }
        },
        "additionalProperties": false,
        "type": "object",
        "required": [
          "environment",
          "expected_current",
          "idempotency_key",
          "commit_sha"
        ],
        "title": "DeployRequest"
      },
      "HTTPValidationError": {
        "properties": {
          "detail": {
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            },
            "type": "array",
            "title": "Detail"
          }
        },
        "type": "object",
        "title": "HTTPValidationError"
      },
      "RestartRequest": {
        "properties": {
          "environment": {
            "type": "string",
            "enum": [
              "staging",
              "production"
            ],
            "title": "Environment"
          },
          "expected_current": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}$",
            "title": "Expected Current"
          },
          "idempotency_key": {
            "type": "string",
            "pattern": "^[A-Za-z0-9._:-]{8,128}$",
            "title": "Idempotency Key"
          },
          "approval_id": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^[0-9a-f]{32}$"
              },
              {
                "type": "null"
              }
            ],
            "title": "Approval Id"
          },
          "target": {
            "type": "string",
            "enum": [
              "api",
              "worker",
              "all"
            ],
            "title": "Target"
          }
        },
        "additionalProperties": false,
        "type": "object",
        "required": [
          "environment",
          "expected_current",
          "idempotency_key",
          "target"
        ],
        "title": "RestartRequest"
      },
      "RollbackRequest": {
        "properties": {
          "environment": {
            "type": "string",
            "enum": [
              "staging",
              "production"
            ],
            "title": "Environment"
          },
          "expected_current": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}$",
            "title": "Expected Current"
          },
          "idempotency_key": {
            "type": "string",
            "pattern": "^[A-Za-z0-9._:-]{8,128}$",
            "title": "Idempotency Key"
          },
          "approval_id": {
            "anyOf": [
              {
                "type": "string",
                "pattern": "^[0-9a-f]{32}$"
              },
              {
                "type": "null"
              }
            ],
            "title": "Approval Id"
          },
          "target": {
            "type": "string",
            "pattern": "^[0-9a-f]{40}$",
            "title": "Target"
          }
        },
        "additionalProperties": false,
        "type": "object",
        "required": [
          "environment",
          "expected_current",
          "idempotency_key",
          "target"
        ],
        "title": "RollbackRequest"
      },
      "ValidationError": {
        "properties": {
          "loc": {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "integer"
                }
              ]
            },
            "type": "array",
            "title": "Location"
          },
          "msg": {
            "type": "string",
            "title": "Message"
          },
          "type": {
            "type": "string",
            "title": "Error Type"
          },
          "input": {
            "title": "Input"
          },
          "ctx": {
            "type": "object",
            "title": "Context"
          }
        },
        "type": "object",
        "required": [
          "loc",
          "msg",
          "type"
        ],
        "title": "ValidationError"
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": [
    {
      "url": "https://ops.deepaha.com"
    }
  ]
}