import { expect, test } from "@playwright/test";
import f from "../tests/relation-review-fixture.json";
import n from "../tests/relation-proposal-fixture.json";
import q from "../tests/relation-queue-fixture.json";
import scope from "../tests/scope-preflight-fixture.json";
test("queue filters current states and clears them on source change and auth failure", async ({ page, context, request }) => {
  await request.get("http://127.0.0.1:3099/queue-reset");
  await context.addCookies([{ name: "deepaha_phase7_reviewer_session", value: "synthetic-browser-reviewer", domain: "127.0.0.1", path: "/", httpOnly: true }]);
  await page.goto(`/review/investigations/${q.current.task_id}/unit-plans/${q.current.target_plan_id}/relations`);
  await expect(page.getByRole("heading", { name: "关系提案审核队列" })).toBeVisible();
  await page.getByLabel("筛选本页审核状态").selectOption("UNREVIEWED");
  await expect(page.getByRole("link", { name: "关系提案 1", exact: true })).toHaveCount(0);
  await expect(page.getByRole("link", { name: "关系提案 2", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("article").getByText("关系提案审核通过", { exact: true })).toBeVisible();
  await request.get("http://127.0.0.1:3099/queue-stale");
  await page.getByRole("button", { name: "重新读取本页" }).click();
  await expect(page.getByRole("article").getByText("依据已变化，旧决定失效", { exact: true })).toHaveCount(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "output/playwright/relations/queue-stale.png", fullPage: true });
  await request.get("http://127.0.0.1:3099/queue-forbidden");
  await page.getByRole("button", { name: "重新读取本页" }).click();
  await expect(page.getByRole("alert")).toBeVisible();
  await expect(page.getByRole("link", { name: "关系提案 1", exact: true })).toHaveCount(0);
});
test("desktop creates from full conditions with literal evidence and refreshes stable detail", async ({ page, context }) => {
  await context.addCookies([{ name: "deepaha_phase7_reviewer_session", value: "synthetic-browser-reviewer", domain: "127.0.0.1", path: "/", httpOnly: true }]);
  const base = `/review/investigations/${n.task}/unit-plans/${n.plan}`;
  await page.goto(`${base}/cross-level`);
  await page.getByRole("link", { name: "从当前条件新建关系提案" }).click();
  await expect(page.getByRole("heading", { name: "新建关系提案" })).toBeVisible();
  for (const id of n.command.condition_ids) await page.getByLabel(`选择条件 ${id}`, { exact: true }).check();
  await page.getByLabel("关系类型").selectOption(n.command.relation);
  await page.getByLabel("提案理由").fill(n.command.reason);
  for (const e of n.command.evidence) {
    await page.getByLabel("官方原文块").selectOption(`${e.block_id}:${e.member_id}`);
    await page.getByLabel("证据用途").selectOption(e.purpose);
    if (e.purpose === "CONDITION") for (const id of e.condition_ids) await page.getByRole("group", { name: "此引文支持的条件" }).getByLabel(new RegExp(id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))).check();
    await page.getByLabel("逐字引文").fill(e.quote);
    await page.getByRole("button", { name: "添加证据", exact: true }).click();
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "output/playwright/relations/desktop-proposal-form.png", fullPage: true });
  await page.getByRole("button", { name: "保存关系提案" }).click();
  await expect(page).toHaveURL(`http://127.0.0.1:3098${base}/relations?proposal=${n.saved.proposal_id}`);
  await page.reload();
  await expect(page.getByRole("heading", { name: "待独立审核" })).toBeVisible();
  await expect(page.getByText(n.command.reason, { exact: true })).toBeVisible();
});
test("desktop saved address, independent decision, refresh and stale state", async ({ page, context, request }) => {
  await request.get("http://127.0.0.1:3099/reset");
  await context.addCookies([{ name: "deepaha_phase7_reviewer_session", value: "synthetic-browser-reviewer", domain: "127.0.0.1", path: "/", httpOnly: true }]);
  const path = `/review/investigations/${f.task}/unit-plans/${f.plan}/relations`;
  await page.goto(path);
  await page.getByRole("link", { name: "关系提案 1", exact: true }).click();
  await expect(page).toHaveURL(`http://127.0.0.1:3098${path}?proposal=${f.saved.proposal_id}`);
  await page.reload();
  await expect(page.getByRole("heading", { name: "待独立审核" })).toBeVisible();
  await page.getByLabel("审核决定").selectOption("APPROVE");
  await page.getByLabel("审核理由").fill(f.approved.decision.reason);
  await page.getByRole("button", { name: "追加审核记录" }).click();
  await expect(page.getByRole("heading", { name: "关系提案审核通过" })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("heading", { name: "关系提案审核通过" })).toBeVisible();
  await request.get("http://127.0.0.1:3099/stale");
  await page.getByRole("button", { name: "重新读取当前状态" }).click();
  await expect(page.getByRole("heading", { name: "依据已变化，旧决定失效" })).toBeVisible();
  await expect(page.getByRole("button", { name: "追加审核记录" })).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: "output/playwright/relations/desktop-stale.png", fullPage: true });
});

for (const width of [1440, 390]) test(`scope preflight at ${width}px preserves boundaries and clears stale results`, async ({ page, context, request }) => {
  await request.get("http://127.0.0.1:3099/scope-current");
  await page.setViewportSize({ width, height: 900 });
  await context.addCookies([{ name: "deepaha_phase7_reviewer_session", value: "synthetic-browser-reviewer", domain: "127.0.0.1", path: "/", httpOnly: true }]);
  const v = scope.current;
  await page.goto(`/review/investigations/${v.task_id}/unit-plans/${v.target_plan_id}/scope-preflight`);
  await expect(page.getByRole("heading", { name: "条件范围预检", exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "查看条件原文与依据" })).toHaveCount(v.conditions.length);
  await expect(page.getByText("关系提案审核通过", { exact: true })).toBeVisible();
  await expect(page.getByText(/不能视为永久有效/)).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: `output/playwright/relations/scope-${width}.png`, fullPage: true });
  await request.get("http://127.0.0.1:3099/scope-stale");
  const reload = page.getByRole("button", { name: "重新读取预检" });
  await reload.focus(); await page.keyboard.press("Enter");
  await expect(page.getByText("依据已变化，旧决定失效", { exact: true })).toHaveCount(2);
  await request.get("http://127.0.0.1:3099/scope-forbidden");
  await reload.click();
  await expect(page.getByRole("alert").filter({ hasText: "没有查看权限" })).toBeVisible();
  await expect(page.getByRole("link", { name: "关系提案 1", exact: true })).toHaveCount(0);
  await request.get("http://127.0.0.1:3099/scope-current");
  await reload.click();
  await expect(page.getByText("关系提案审核通过", { exact: true })).toBeVisible();
});
