"""phase1_domain_evidence

Revision ID: 20260821_0001
Revises:
Create Date: 2026-08-21 19:51:59.279653
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260821_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("source_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=False),
        sa.Column("authority_name", sa.Text(), nullable=False),
        sa.Column("tier", sa.String(length=32), nullable=False),
        sa.Column("jurisdiction", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "public_id ~ '^src_[0-9a-f]{32}$'", name=op.f("ck_sources_public_id_format")
        ),
        sa.CheckConstraint(
            "tier in ('OFFICIAL_PRIMARY', 'OFFICIAL_AGGREGATOR', "
            "'TRUSTED_SECONDARY', 'COMMUNITY_SIGNAL')",
            name=op.f("ck_sources_tier_values"),
        ),
        sa.CheckConstraint("updated_at >= created_at", name=op.f("ck_sources_timestamp_order")),
        sa.CheckConstraint(
            "uuid_extract_version(source_id) = 7", name=op.f("ck_sources_source_id_uuid7")
        ),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_sources")),
        sa.UniqueConstraint("canonical_url", name=op.f("uq_sources_canonical_url")),
        sa.UniqueConstraint("public_id", name=op.f("uq_sources_public_id")),
    )
    op.create_table(
        "raw_artifacts",
        sa.Column("artifact_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("resolved_url", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("media_type", sa.Text(), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_bucket", sa.String(length=63), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("collector_version", sa.String(length=128), nullable=False),
        sa.Column("metadata_schema_version", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "content_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_raw_artifacts_content_sha256_format")
        ),
        sa.CheckConstraint(
            "object_key = 'raw/sha256/' || "
            "substring(content_sha256 from 1 for 2) || '/' || content_sha256",
            name=op.f("ck_raw_artifacts_content_addressed_object_key"),
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_raw_artifacts_positive_byte_size")),
        sa.CheckConstraint(
            "http_status is null or http_status between 100 and 599",
            name=op.f("ck_raw_artifacts_http_status_range"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(artifact_id) = 7", name=op.f("ck_raw_artifacts_artifact_id_uuid7")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_raw_artifacts_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("artifact_id", name=op.f("pk_raw_artifacts")),
        sa.UniqueConstraint("source_id", "content_sha256", name=op.f("uq_raw_artifacts_source_id")),
    )
    op.create_table(
        "documents",
        sa.Column("document_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("language", sa.String(length=35), nullable=False),
        sa.Column("extracted_text_uri", sa.Text(), nullable=True),
        sa.Column("parser_name", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("parse_confidence", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "parse_confidence is null or parse_confidence between 0 and 1",
            name=op.f("ck_documents_parse_confidence_range"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(document_id) = 7", name=op.f("ck_documents_document_id_uuid7")
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["raw_artifacts.artifact_id"],
            name=op.f("fk_documents_artifact_id_raw_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_documents")),
        sa.UniqueConstraint(
            "artifact_id", "parser_name", "parser_version", name=op.f("uq_documents_artifact_id")
        ),
        sa.UniqueConstraint("document_id", "artifact_id", name=op.f("uq_documents_document_id")),
    )
    op.create_table(
        "opportunities",
        sa.Column("opportunity_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("canonical_title", sa.Text(), nullable=False),
        sa.Column("issuer_name", sa.Text(), nullable=False),
        sa.Column("jurisdiction", sa.Text(), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("publication_status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "public_id ~ '^opp_[0-9a-f]{32}$'", name=op.f("ck_opportunities_public_id_format")
        ),
        sa.CheckConstraint(
            "publication_status in ('INTERNAL', 'READY', 'PUBLISHED', 'WITHDRAWN')",
            name=op.f("ck_opportunities_publication_status_values"),
        ),
        sa.CheckConstraint(
            "status in ('DRAFT', 'OPEN', 'CLOSING_SOON', 'CLOSED', "
            "'CANCELLED', 'SUPERSEDED', 'UNKNOWN')",
            name=op.f("ck_opportunities_status_values"),
        ),
        sa.CheckConstraint(
            "type in ('PUBLIC_INSTITUTION_JOB', 'STATE_OWNED_ENTERPRISE_JOB', "
            "'CIVIL_SERVICE', 'GRASSROOTS_PROGRAM', 'YOUTH_POLICY_BENEFIT', "
            "'POSTGRAD_RECOMMENDATION', 'ADMISSION_CHANGE')",
            name=op.f("ck_opportunities_type_values"),
        ),
        sa.CheckConstraint(
            "current_version is null or current_version >= 1",
            name=op.f("ck_opportunities_positive_current_version"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_opportunities_timestamp_order")
        ),
        sa.CheckConstraint(
            "uuid_extract_version(opportunity_id) = 7",
            name=op.f("ck_opportunities_opportunity_id_uuid7"),
        ),
        sa.PrimaryKeyConstraint("opportunity_id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("public_id", name=op.f("uq_opportunities_public_id")),
    )
    op.create_table(
        "evidence_refs",
        sa.Column("evidence_ref_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("locator_kind", sa.String(length=32), nullable=False),
        sa.Column("locator_value", sa.Text(), nullable=False),
        sa.Column("quote_sha256", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "locator_kind <> 'full_document' or locator_value = '*'",
            name=op.f("ck_evidence_refs_full_document_locator_value"),
        ),
        sa.CheckConstraint(
            "locator_kind in ('page', 'paragraph', 'css_selector', 'text_span', 'full_document')",
            name=op.f("ck_evidence_refs_locator_kind_values"),
        ),
        sa.CheckConstraint(
            "quote_sha256 is null or quote_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_evidence_refs_quote_sha256_format"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(evidence_ref_id) = 7",
            name=op.f("ck_evidence_refs_evidence_ref_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "artifact_id"],
            ["documents.document_id", "documents.artifact_id"],
            name=op.f("fk_evidence_refs_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("evidence_ref_id", name=op.f("pk_evidence_refs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_refs")
    op.drop_table("opportunities")
    op.drop_table("documents")
    op.drop_table("raw_artifacts")
    op.drop_table("sources")
    # ### end Alembic commands ###
