"""phase8_deadline_reminders

Revision ID: 20260822_0008
Revises: 20260822_0007
Create Date: 2026-08-22 22:13:45.478901
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260822_0008"
down_revision: str | None = "20260822_0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

PHASE8_TABLES = (
    "reminder_preference_snapshots",
    "reminder_preference_idempotency_records",
    "notification_outbox",
    "notification_delivery_attempts",
    "test_inbox_entries",
)
IMMUTABLE_PHASE8_TABLES = (
    "reminder_preference_snapshots",
    "notification_delivery_attempts",
    "test_inbox_entries",
)


def upgrade() -> None:
    """Add governed deadline-change reminder persistence and test delivery."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_opportunity_events_reminder_binding",
        "opportunity_events",
        ["event_id", "opportunity_id", "to_version"],
    )
    op.create_table(
        "reminder_preference_snapshots",
        sa.Column("preference_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("preference_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("predecessor_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("reminder_kind", sa.String(length=32), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cadence", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=24), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("preference_policy_version", sa.String(length=48), nullable=False),
        sa.Column("contract_version", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "cadence = 'AS_SOON_AS_GOVERNED'",
            name=op.f("ck_reminder_preference_snapshots_cadence_value"),
        ),
        sa.CheckConstraint(
            "contract_version = '0.7.0'",
            name=op.f("ck_reminder_preference_snapshots_contract_version_value"),
        ),
        sa.CheckConstraint(
            "preference_policy_version = 'phase8-deadline-reminder-v1'",
            name=op.f("ck_reminder_preference_snapshots_policy_version_value"),
        ),
        sa.CheckConstraint(
            "reminder_kind = 'DEADLINE_CHANGED'",
            name=op.f("ck_reminder_preference_snapshots_reminder_kind_value"),
        ),
        sa.CheckConstraint(
            "target = 'TEST_INBOX'", name=op.f("ck_reminder_preference_snapshots_target_value")
        ),
        sa.CheckConstraint(
            "(version = 1 and predecessor_snapshot_id is null) or "
            "(version > 1 and predecessor_snapshot_id is not null)",
            name=op.f("ck_reminder_preference_snapshots_predecessor_version_coherence"),
        ),
        sa.CheckConstraint(
            "actor_user_id = user_id", name=op.f("ck_reminder_preference_snapshots_actor_is_owner")
        ),
        sa.CheckConstraint(
            "predecessor_snapshot_id is null or predecessor_snapshot_id <> preference_snapshot_id",
            name=op.f("ck_reminder_preference_snapshots_predecessor_not_self"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(preference_id) = 7",
            name=op.f("ck_reminder_preference_snapshots_preference_id_uuid7"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(preference_snapshot_id) = 7",
            name=op.f("ck_reminder_preference_snapshots_preference_snapshot_id_uuid7"),
        ),
        sa.CheckConstraint(
            "version >= 1", name=op.f("ck_reminder_preference_snapshots_positive_version")
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["personal_users.user_id"],
            name=op.f("fk_reminder_preference_snapshots_actor_user_id_personal_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["predecessor_snapshot_id"],
            ["reminder_preference_snapshots.preference_snapshot_id"],
            name=op.f(
                "fk_reminder_preference_snapshots_predecessor_snapshot_id_reminder_preference_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["personal_users.user_id"],
            name=op.f("fk_reminder_preference_snapshots_user_id_personal_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "preference_snapshot_id", name=op.f("pk_reminder_preference_snapshots")
        ),
        sa.UniqueConstraint(
            "preference_id", "version", name="uq_reminder_preference_stream_version"
        ),
        sa.UniqueConstraint(
            "user_id",
            "reminder_kind",
            "version",
            name="uq_reminder_preference_owner_kind_version",
        ),
        sa.UniqueConstraint(
            "preference_snapshot_id", "user_id", name="uq_reminder_preference_snapshot_owner"
        ),
    )
    op.create_index(
        "ix_reminder_preference_snapshots_owner_latest",
        "reminder_preference_snapshots",
        ["user_id", "reminder_kind", sa.text("version DESC")],
        unique=False,
    )
    op.create_table(
        "reminder_preference_idempotency_records",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("operation", sa.String(length=64), nullable=False),
        sa.Column("key_sha256", sa.String(length=64), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("resource_kind", sa.String(length=24), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("response_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "key_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_reminder_preference_idempotency_records_key_sha256_format"),
        ),
        sa.CheckConstraint(
            "request_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_reminder_preference_idempotency_records_request_hash_format"),
        ),
        sa.CheckConstraint(
            "resource_kind = 'PREFERENCE'",
            name=op.f("ck_reminder_preference_idempotency_records_resource_kind_value"),
        ),
        sa.CheckConstraint(
            "length(btrim(operation)) >= 1",
            name=op.f("ck_reminder_preference_idempotency_records_operation_nonempty"),
        ),
        sa.CheckConstraint(
            "response_version >= 1",
            name=op.f("ck_reminder_preference_idempotency_records_positive_version"),
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"],
            ["reminder_preference_snapshots.preference_snapshot_id"],
            name=op.f(
                "fk_reminder_preference_idempotency_records_resource_id_reminder_preference_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["personal_users.user_id"],
            name=op.f("fk_reminder_preference_idempotency_records_user_id_personal_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "user_id",
            "operation",
            "key_sha256",
            name=op.f("pk_reminder_preference_idempotency_records"),
        ),
    )
    op.create_table(
        "notification_outbox",
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=False),
        sa.Column("old_closes_on", sa.Date(), nullable=False),
        sa.Column("new_closes_on", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("previous_evidence_ref_id", sa.Uuid(), nullable=False),
        sa.Column("current_evidence_ref_id", sa.Uuid(), nullable=False),
        sa.Column("action_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("preference_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("user_state_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("consent_version", sa.String(length=32), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reminder_kind", sa.String(length=32), nullable=False),
        sa.Column("cadence", sa.String(length=32), nullable=False),
        sa.Column("target", sa.String(length=24), nullable=False),
        sa.Column("contract_version", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=64), nullable=True),
        sa.Column("terminal_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "(status = 'LEASED' and lease_token is not null and lease_until is not null "
            "and claimed_at is not null) or (status <> 'LEASED' and lease_token is null "
            "and lease_until is null and claimed_at is null)",
            name=op.f("ck_notification_outbox_lease_state_coherence"),
        ),
        sa.CheckConstraint(
            "(status = 'WAITING_GOVERNANCE' and available_at is null) or "
            "(status <> 'WAITING_GOVERNANCE' and available_at is not null)",
            name=op.f("ck_notification_outbox_availability_state_coherence"),
        ),
        sa.CheckConstraint(
            "(status in ('DELIVERED', 'SUPPRESSED', 'FAILED') and terminal_at is not null) or "
            "(status not in ('DELIVERED', 'SUPPRESSED', 'FAILED') and terminal_at is null)",
            name=op.f("ck_notification_outbox_terminal_state_coherence"),
        ),
        sa.CheckConstraint(
            "cadence = 'AS_SOON_AS_GOVERNED'", name=op.f("ck_notification_outbox_cadence_value")
        ),
        sa.CheckConstraint(
            "contract_version = '0.7.0'", name=op.f("ck_notification_outbox_contract_version_value")
        ),
        sa.CheckConstraint(
            "last_error_code is null or last_error_code ~ '^[A-Z][A-Z0-9_]{0,63}$'",
            name=op.f("ck_notification_outbox_last_error_code_format"),
        ),
        sa.CheckConstraint(
            "old_closes_on <> new_closes_on and "
            "((direction = 'ADVANCED' and new_closes_on < old_closes_on) or "
            "(direction = 'EXTENDED' and new_closes_on > old_closes_on))",
            name=op.f("ck_notification_outbox_deadline_direction_coherence"),
        ),
        sa.CheckConstraint(
            "reminder_kind = 'DEADLINE_CHANGED'",
            name=op.f("ck_notification_outbox_reminder_kind_value"),
        ),
        sa.CheckConstraint(
            "status in ('WAITING_GOVERNANCE', 'AVAILABLE', 'LEASED', "
            "'DELIVERED', 'SUPPRESSED', 'FAILED')",
            name=op.f("ck_notification_outbox_status_values"),
        ),
        sa.CheckConstraint(
            "target = 'TEST_INBOX'", name=op.f("ck_notification_outbox_target_value")
        ),
        sa.CheckConstraint(
            "attempt_count between 0 and 3", name=op.f("ck_notification_outbox_attempt_count_range")
        ),
        sa.CheckConstraint(
            "to_version = from_version + 1",
            name=op.f("ck_notification_outbox_consecutive_versions"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(reminder_id) = 7",
            name=op.f("ck_notification_outbox_reminder_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["action_snapshot_id"],
            ["personal_action_snapshots.action_snapshot_id"],
            name=op.f("fk_notification_outbox_action_snapshot_id_personal_action_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["current_evidence_ref_id"],
            ["evidence_refs.evidence_ref_id"],
            name=op.f("fk_notification_outbox_current_evidence_ref_id_evidence_refs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id", "opportunity_id", "to_version"],
            [
                "opportunity_events.event_id",
                "opportunity_events.opportunity_id",
                "opportunity_events.to_version",
            ],
            name=op.f("fk_notification_outbox_event_id_opportunity_events"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id", "to_version"],
            ["opportunity_versions.opportunity_id", "opportunity_versions.version"],
            name=op.f("fk_notification_outbox_opportunity_id_opportunity_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["preference_snapshot_id"],
            ["reminder_preference_snapshots.preference_snapshot_id"],
            name=op.f(
                "fk_notification_outbox_preference_snapshot_id_reminder_preference_snapshots"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["previous_evidence_ref_id"],
            ["evidence_refs.evidence_ref_id"],
            name=op.f("fk_notification_outbox_previous_evidence_ref_id_evidence_refs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["personal_users.user_id"],
            name=op.f("fk_notification_outbox_user_id_personal_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_state_snapshot_id"],
            ["user_state_snapshots.user_state_snapshot_id"],
            name=op.f("fk_notification_outbox_user_state_snapshot_id_user_state_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("reminder_id", name=op.f("pk_notification_outbox")),
        sa.UniqueConstraint(
            "user_id",
            "event_id",
            "to_version",
            "reminder_kind",
            "target",
            name="uq_notification_outbox_logical_delivery",
        ),
    )
    op.create_index(
        "ix_notification_outbox_available",
        "notification_outbox",
        ["status", "next_attempt_at", "reminder_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_expired_lease",
        "notification_outbox",
        ["status", "lease_until", "reminder_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_outbox_governance_wait",
        "notification_outbox",
        ["status", "created_at", "reminder_id"],
        unique=False,
    )
    op.create_table(
        "notification_delivery_attempts",
        sa.Column("delivery_attempt_id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=False),
        sa.Column("adapter", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contract_version", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "(outcome = 'SUCCEEDED' and error_code is null) or "
            "(outcome <> 'SUCCEEDED' and error_code is not null)",
            name=op.f("ck_notification_delivery_attempts_outcome_error_coherence"),
        ),
        sa.CheckConstraint(
            "adapter = 'POSTGRES_TEST_INBOX'",
            name=op.f("ck_notification_delivery_attempts_adapter_value"),
        ),
        sa.CheckConstraint(
            "contract_version = '0.7.0'",
            name=op.f("ck_notification_delivery_attempts_contract_version_value"),
        ),
        sa.CheckConstraint(
            "error_code is null or error_code ~ '^[A-Z][A-Z0-9_]{0,63}$'",
            name=op.f("ck_notification_delivery_attempts_error_code_format"),
        ),
        sa.CheckConstraint(
            "outcome in ('SUCCEEDED', 'TRANSIENT_FAILURE', 'PERMANENT_FAILURE')",
            name=op.f("ck_notification_delivery_attempts_outcome_values"),
        ),
        sa.CheckConstraint(
            "attempt_number between 1 and 3",
            name=op.f("ck_notification_delivery_attempts_attempt_number_range"),
        ),
        sa.CheckConstraint(
            "completed_at >= started_at",
            name=op.f("ck_notification_delivery_attempts_attempt_time_order"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(delivery_attempt_id) = 7",
            name=op.f("ck_notification_delivery_attempts_delivery_attempt_id_uuid7"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(lease_token) = 7",
            name=op.f("ck_notification_delivery_attempts_lease_token_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["notification_outbox.reminder_id"],
            name=op.f("fk_notification_delivery_attempts_reminder_id_notification_outbox"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "delivery_attempt_id", name=op.f("pk_notification_delivery_attempts")
        ),
        sa.UniqueConstraint(
            "reminder_id", "attempt_number", name="uq_notification_delivery_attempt_number"
        ),
    )
    op.create_table(
        "test_inbox_entries",
        sa.Column("inbox_entry_id", sa.Uuid(), nullable=False),
        sa.Column("reminder_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_id", sa.Uuid(), nullable=False),
        sa.Column("opportunity_public_id", sa.String(length=36), nullable=False),
        sa.Column("opportunity_title", sa.String(length=300), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("from_version", sa.Integer(), nullable=False),
        sa.Column("to_version", sa.Integer(), nullable=False),
        sa.Column("old_closes_on", sa.Date(), nullable=False),
        sa.Column("new_closes_on", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("previous_evidence_ref_id", sa.Uuid(), nullable=False),
        sa.Column("current_evidence_ref_id", sa.Uuid(), nullable=False),
        sa.Column("previous_official_url", sa.String(length=2048), nullable=False),
        sa.Column("current_official_url", sa.String(length=2048), nullable=False),
        sa.Column("personal_detail_path", sa.String(length=80), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target", sa.String(length=24), nullable=False),
        sa.Column("contract_version", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "contract_version = '0.7.0'", name=op.f("ck_test_inbox_entries_contract_version_value")
        ),
        sa.CheckConstraint(
            "old_closes_on <> new_closes_on and "
            "((direction = 'ADVANCED' and new_closes_on < old_closes_on) or "
            "(direction = 'EXTENDED' and new_closes_on > old_closes_on))",
            name=op.f("ck_test_inbox_entries_deadline_direction_coherence"),
        ),
        sa.CheckConstraint(
            "opportunity_public_id ~ '^opp_[0-9a-f]{32}$'",
            name=op.f("ck_test_inbox_entries_opportunity_public_id_format"),
        ),
        sa.CheckConstraint(
            "personal_detail_path = '/me/opportunities/' || opportunity_public_id",
            name=op.f("ck_test_inbox_entries_personal_detail_path_value"),
        ),
        sa.CheckConstraint(
            "target = 'TEST_INBOX'", name=op.f("ck_test_inbox_entries_target_value")
        ),
        sa.CheckConstraint(
            "delivered_at >= detected_at", name=op.f("ck_test_inbox_entries_delivery_time_order")
        ),
        sa.CheckConstraint(
            "length(btrim(opportunity_title)) >= 1",
            name=op.f("ck_test_inbox_entries_opportunity_title_nonempty"),
        ),
        sa.CheckConstraint(
            "to_version = from_version + 1", name=op.f("ck_test_inbox_entries_consecutive_versions")
        ),
        sa.CheckConstraint(
            "uuid_extract_version(inbox_entry_id) = 7",
            name=op.f("ck_test_inbox_entries_inbox_entry_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["reminder_id"],
            ["notification_outbox.reminder_id"],
            name=op.f("fk_test_inbox_entries_reminder_id_notification_outbox"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["personal_users.user_id"],
            name=op.f("fk_test_inbox_entries_user_id_personal_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("inbox_entry_id", name=op.f("pk_test_inbox_entries")),
        sa.UniqueConstraint("reminder_id", name="uq_test_inbox_entries_reminder"),
    )
    op.create_index(
        "ix_test_inbox_entries_owner_delivery",
        "test_inbox_entries",
        ["user_id", sa.text("delivered_at DESC"), sa.text("inbox_entry_id DESC")],
        unique=False,
    )
    op.create_index(
        "ix_personal_action_snapshots_opportunity_owner_version",
        "personal_action_snapshots",
        ["opportunity_id", "user_id", sa.text("version DESC")],
        unique=False,
    )
    op.create_index(
        "ix_user_state_snapshots_owner_version",
        "user_state_snapshots",
        ["user_id", sa.text("version DESC")],
        unique=False,
    )
    op.execute(
        """
        CREATE FUNCTION phase8_reject_immutable_mutation()
        RETURNS trigger
        LANGUAGE plpgsql
        AS $$
        BEGIN
            RAISE EXCEPTION 'Phase 8 governed reminder fact is immutable';
        END;
        $$
        """
    )
    for table_name in IMMUTABLE_PHASE8_TABLES:
        op.execute(
            sa.text(
                f"CREATE TRIGGER phase8_reject_mutation "
                f"BEFORE UPDATE OR DELETE ON {table_name} "
                "FOR EACH ROW EXECUTE FUNCTION phase8_reject_immutable_mutation()"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuse to discard any Phase 8 reminder evidence."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    for table_name in PHASE8_TABLES:
        populated = connection.execute(
            sa.text(f"SELECT EXISTS (SELECT 1 FROM {table_name} LIMIT 1)")
        ).scalar_one()
        if populated:
            raise RuntimeError("cannot downgrade Phase 8 while reminder rows exist")

    for table_name in IMMUTABLE_PHASE8_TABLES:
        op.execute(sa.text(f"DROP TRIGGER phase8_reject_mutation ON {table_name}"))
    op.execute("DROP FUNCTION phase8_reject_immutable_mutation()")
    op.drop_index("ix_user_state_snapshots_owner_version", table_name="user_state_snapshots")
    op.drop_index(
        "ix_personal_action_snapshots_opportunity_owner_version",
        table_name="personal_action_snapshots",
    )
    op.drop_index("ix_test_inbox_entries_owner_delivery", table_name="test_inbox_entries")
    op.drop_table("test_inbox_entries")
    op.drop_table("notification_delivery_attempts")
    op.drop_index("ix_notification_outbox_governance_wait", table_name="notification_outbox")
    op.drop_index("ix_notification_outbox_expired_lease", table_name="notification_outbox")
    op.drop_index("ix_notification_outbox_available", table_name="notification_outbox")
    op.drop_table("notification_outbox")
    op.drop_constraint(
        "uq_opportunity_events_reminder_binding", "opportunity_events", type_="unique"
    )
    op.drop_table("reminder_preference_idempotency_records")
    op.drop_index(
        "ix_reminder_preference_snapshots_owner_latest", table_name="reminder_preference_snapshots"
    )
    op.drop_table("reminder_preference_snapshots")
    # ### end Alembic commands ###
