"""phase2_observation_and_locators

Revision ID: 20260821_0002
Revises: 20260821_0001
Create Date: 2026-08-21 23:06:21.706159
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260821_0002"
down_revision: str | None = "20260821_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OPEN_LICENSE_CHECK = (
    "content_use_basis <> 'OPEN_LICENSE' or (license_name is not null and license_url is not null)"
)
CONTENT_USE_BASIS_CHECK = (
    "content_use_basis in ('OPEN_LICENSE', 'OFFICIAL_PUBLIC_ACCESS', 'LINK_ONLY', 'UNKNOWN')"
)
ACTIVE_POLICY_CHECK = (
    "not active or (robots_decision in ('ALLOWED', 'NOT_APPLICABLE') "
    "and content_use_basis <> 'UNKNOWN')"
)
CAPTURE_OUTCOME_CHECK = (
    "(outcome = 'SUCCEEDED' and artifact_id is not null and error_code is null) or "
    "(outcome = 'NOT_MODIFIED' and http_status = 304 and artifact_id is not null "
    "and error_code is null) or "
    "(outcome = 'FAILED' and artifact_id is null and error_code is not null)"
)
PARSE_OUTCOME_CHECK = (
    "(outcome = 'SUCCEEDED' and document_id is not null and error_code is null) or "
    "(outcome = 'NEEDS_REVIEW' and document_id is not null) or "
    "(outcome = 'FAILED' and document_id is null and error_code is not null)"
)
LOCATOR_PAYLOAD_SHAPE_CHECK = (
    "locator_schema_version <> '0.2.0' or ("
    "jsonb_typeof(locator_payload) = 'object' and "
    "locator_payload->>'schema_version' = '0.2.0' and "
    "locator_payload->>'kind' = locator_kind and ("
    "(locator_kind = 'html_selector' and locator_payload ?& "
    "array['schema_version', 'kind', 'selector', 'text_sha256'] and "
    "locator_payload - array['schema_version', 'kind', 'selector', 'text_sha256'] "
    "= '{}'::jsonb and "
    'locator_payload @@ \'$.selector.type() == "string" && $.selector != ""\' and '
    "locator_payload->>'text_sha256' ~ '^[0-9a-f]{64}$') or "
    "(locator_kind = 'pdf_page_text' and locator_payload ?& "
    "array['schema_version', 'kind', 'page_number', 'text_start', 'text_end', "
    "'text_sha256'] and locator_payload - array['schema_version', 'kind', "
    "'page_number', 'text_start', 'text_end', 'text_sha256'] = '{}'::jsonb and "
    'locator_payload @@ \'$.page_number.type() == "number" && $.page_number >= 1 '
    '&& $.text_start.type() == "number" && $.text_start >= 0 '
    '&& $.text_end.type() == "number" && $.text_end > $.text_start\' and '
    "locator_payload->>'text_sha256' ~ '^[0-9a-f]{64}$') or "
    "(locator_kind = 'spreadsheet_range' and locator_payload ?& "
    "array['schema_version', 'kind', 'sheet_name', 'start_row', 'end_row', "
    "'start_column', 'end_column', 'cells_sha256'] and locator_payload - "
    "array['schema_version', 'kind', 'sheet_name', 'start_row', 'end_row', "
    "'start_column', 'end_column', 'cells_sha256'] = '{}'::jsonb and "
    'locator_payload @@ \'$.sheet_name.type() == "string" && $.sheet_name != "" '
    '&& $.start_row.type() == "number" && $.start_row >= 1 '
    '&& $.end_row.type() == "number" && $.end_row >= $.start_row '
    '&& $.start_column.type() == "number" && $.start_column >= 1 '
    '&& $.end_column.type() == "number" && $.end_column >= $.start_column\' and '
    "locator_payload->>'cells_sha256' ~ '^[0-9a-f]{64}$')"
    "))"
)
LOCATOR_SCHEMA_FORM_CHECK = (
    "(locator_schema_version = '0.1.0' and "
    "locator_kind in ('page', 'paragraph', 'css_selector', 'text_span', 'full_document') "
    "and locator_value is not null and locator_payload is null) or "
    "(locator_schema_version = '0.2.0' and "
    "locator_kind in ('html_selector', 'pdf_page_text', 'spreadsheet_range') "
    "and locator_value is null and locator_payload is not null)"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_endpoints",
        sa.Column("endpoint_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("allowed_hosts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expected_media_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("browser_policy", sa.String(length=16), nullable=False),
        sa.Column("minimum_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("robots_url", sa.Text(), nullable=True),
        sa.Column("robots_decision", sa.String(length=16), nullable=False),
        sa.Column("robots_checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_use_basis", sa.String(length=32), nullable=False),
        sa.Column("license_name", sa.Text(), nullable=True),
        sa.Column("license_url", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("fixture_storage_allowed", sa.Boolean(), nullable=False),
        sa.Column("usage_note", sa.Text(), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "browser_policy in ('NEVER', 'FALLBACK')",
            name=op.f("ck_source_endpoints_browser_policy_values"),
        ),
        sa.CheckConstraint(
            OPEN_LICENSE_CHECK,
            name=op.f("ck_source_endpoints_open_license_metadata"),
        ),
        sa.CheckConstraint(
            CONTENT_USE_BASIS_CHECK,
            name=op.f("ck_source_endpoints_content_use_basis_values"),
        ),
        sa.CheckConstraint(
            ACTIVE_POLICY_CHECK,
            name=op.f("ck_source_endpoints_active_policy_approved"),
        ),
        sa.CheckConstraint(
            "not fixture_storage_allowed or content_use_basis = 'OPEN_LICENSE'",
            name=op.f("ck_source_endpoints_fixture_storage_permission"),
        ),
        sa.CheckConstraint(
            "robots_decision in ('ALLOWED', 'NOT_APPLICABLE', 'DISALLOWED', 'UNKNOWN')",
            name=op.f("ck_source_endpoints_robots_decision_values"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(allowed_hosts) >= 1",
            name=op.f("ck_source_endpoints_allowed_hosts_nonempty"),
        ),
        sa.CheckConstraint(
            "jsonb_array_length(expected_media_types) >= 1",
            name=op.f("ck_source_endpoints_expected_media_types_nonempty"),
        ),
        sa.CheckConstraint(
            "max_attempts between 1 and 3", name=op.f("ck_source_endpoints_max_attempts_range")
        ),
        sa.CheckConstraint(
            "minimum_interval_seconds >= 1",
            name=op.f("ck_source_endpoints_minimum_interval_positive"),
        ),
        sa.CheckConstraint(
            "timeout_seconds between 1 and 120",
            name=op.f("ck_source_endpoints_timeout_seconds_range"),
        ),
        sa.CheckConstraint(
            "updated_at >= created_at", name=op.f("ck_source_endpoints_timestamp_order")
        ),
        sa.CheckConstraint(
            "uuid_extract_version(endpoint_id) = 7",
            name=op.f("ck_source_endpoints_endpoint_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
            name=op.f("fk_source_endpoints_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("endpoint_id", name=op.f("pk_source_endpoints")),
        sa.UniqueConstraint(
            "endpoint_id", "source_id", name=op.f("uq_source_endpoints_endpoint_id")
        ),
        sa.UniqueConstraint(
            "source_id", "url", "policy_version", name=op.f("uq_source_endpoints_source_id")
        ),
    )
    op.create_unique_constraint(
        op.f("uq_raw_artifacts_artifact_id"), "raw_artifacts", ["artifact_id", "source_id"]
    )
    op.create_table(
        "capture_observations",
        sa.Column("observation_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("collection_run_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("resolved_url", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("response_etag", sa.Text(), nullable=True),
        sa.Column("response_last_modified", sa.Text(), nullable=True),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("collector_name", sa.String(length=128), nullable=False),
        sa.Column("collector_version", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            CAPTURE_OUTCOME_CHECK,
            name=op.f("ck_capture_observations_outcome_state"),
        ),
        sa.CheckConstraint(
            "outcome in ('SUCCEEDED', 'NOT_MODIFIED', 'FAILED')",
            name=op.f("ck_capture_observations_outcome_values"),
        ),
        sa.CheckConstraint(
            "attempt_number >= 1", name=op.f("ck_capture_observations_attempt_number_positive")
        ),
        sa.CheckConstraint(
            "completed_at >= started_at", name=op.f("ck_capture_observations_timestamp_order")
        ),
        sa.CheckConstraint(
            "http_status is null or http_status between 100 and 599",
            name=op.f("ck_capture_observations_http_status_range"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(collection_run_id) = 7",
            name=op.f("ck_capture_observations_collection_run_id_uuid7"),
        ),
        sa.CheckConstraint(
            "uuid_extract_version(observation_id) = 7",
            name=op.f("ck_capture_observations_observation_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id", "source_id"],
            ["raw_artifacts.artifact_id", "raw_artifacts.source_id"],
            name=op.f("fk_capture_observations_artifact_id_raw_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id", "source_id"],
            ["source_endpoints.endpoint_id", "source_endpoints.source_id"],
            name=op.f("fk_capture_observations_endpoint_id_source_endpoints"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_capture_observations")),
        sa.UniqueConstraint(
            "collection_run_id",
            "attempt_number",
            name=op.f("uq_capture_observations_collection_run_id"),
        ),
    )
    op.create_table(
        "parse_attempts",
        sa.Column(
            "parse_attempt_id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("parser_name", sa.String(length=128), nullable=False),
        sa.Column("parser_version", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("input_media_type", sa.Text(), nullable=False),
        sa.CheckConstraint(
            PARSE_OUTCOME_CHECK,
            name=op.f("ck_parse_attempts_outcome_state"),
        ),
        sa.CheckConstraint(
            "outcome in ('SUCCEEDED', 'NEEDS_REVIEW', 'FAILED')",
            name=op.f("ck_parse_attempts_outcome_values"),
        ),
        sa.CheckConstraint(
            "completed_at >= started_at", name=op.f("ck_parse_attempts_timestamp_order")
        ),
        sa.CheckConstraint(
            "uuid_extract_version(parse_attempt_id) = 7",
            name=op.f("ck_parse_attempts_parse_attempt_id_uuid7"),
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["raw_artifacts.artifact_id"],
            name=op.f("fk_parse_attempts_artifact_id_raw_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "artifact_id"],
            ["documents.document_id", "documents.artifact_id"],
            name=op.f("fk_parse_attempts_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("parse_attempt_id", name=op.f("pk_parse_attempts")),
        sa.UniqueConstraint(
            "artifact_id",
            "parser_name",
            "parser_version",
            name=op.f("uq_parse_attempts_artifact_id"),
        ),
    )
    op.add_column(
        "evidence_refs",
        sa.Column(
            "locator_schema_version",
            sa.String(length=16),
            server_default=sa.text("'0.1.0'"),
            nullable=False,
        ),
    )
    op.add_column(
        "evidence_refs",
        sa.Column("locator_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.alter_column("evidence_refs", "locator_value", existing_type=sa.TEXT(), nullable=True)
    op.drop_constraint(
        op.f("ck_evidence_refs_full_document_locator_value"),
        "evidence_refs",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_evidence_refs_locator_kind_values"),
        "evidence_refs",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_evidence_refs_locator_kind_values"),
        "evidence_refs",
        "locator_kind in ('page', 'paragraph', 'css_selector', 'text_span', "
        "'full_document', 'html_selector', 'pdf_page_text', 'spreadsheet_range')",
    )
    op.create_check_constraint(
        op.f("ck_evidence_refs_full_document_locator_value"),
        "evidence_refs",
        "locator_schema_version <> '0.1.0' or locator_kind <> 'full_document' "
        "or locator_value = '*'",
    )
    op.create_check_constraint(
        op.f("ck_evidence_refs_locator_payload_shape"),
        "evidence_refs",
        LOCATOR_PAYLOAD_SHAPE_CHECK,
    )
    op.create_check_constraint(
        op.f("ck_evidence_refs_locator_schema_form"),
        "evidence_refs",
        LOCATOR_SCHEMA_FORM_CHECK,
    )
    op.drop_constraint(op.f("ck_opportunities_type_values"), "opportunities", type_="check")
    op.create_check_constraint(
        op.f("ck_opportunities_type_values"),
        "opportunities",
        "type in ('PUBLIC_INSTITUTION_JOB', 'STATE_OWNED_ENTERPRISE_JOB', "
        "'CIVIL_SERVICE', 'GRASSROOTS_PROGRAM', 'YOUTH_POLICY_BENEFIT', "
        "'POSTGRAD_RECOMMENDATION', 'ADMISSION_CHANGE', 'COMPETITION', "
        "'RESEARCH_PROGRAM', 'SCHOLARSHIP', 'YOUTH_DEVELOPMENT_PROGRAM')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    for table_name in ("capture_observations", "parse_attempts", "source_endpoints"):
        contains_rows = connection.scalar(
            sa.text(f"select exists(select 1 from {table_name} limit 1)")
        )
        if contains_rows:
            raise RuntimeError(f"cannot downgrade Phase 2 while {table_name} contains v0.2 data")
    has_structured_locator = connection.scalar(
        sa.text(
            "select exists(select 1 from evidence_refs "
            "where locator_schema_version <> '0.1.0' limit 1)"
        )
    )
    if has_structured_locator:
        raise RuntimeError("cannot downgrade Phase 2 while structured locators exist")
    has_phase2_opportunity_type = connection.scalar(
        sa.text(
            "select exists(select 1 from opportunities where type in "
            "('COMPETITION', 'RESEARCH_PROGRAM', 'SCHOLARSHIP', "
            "'YOUTH_DEVELOPMENT_PROGRAM') limit 1)"
        )
    )
    if has_phase2_opportunity_type:
        raise RuntimeError("cannot downgrade Phase 2 while v0.2 opportunity types exist")

    op.drop_table("parse_attempts")
    op.drop_table("capture_observations")
    op.drop_table("source_endpoints")
    op.drop_constraint(op.f("ck_opportunities_type_values"), "opportunities", type_="check")
    op.create_check_constraint(
        op.f("ck_opportunities_type_values"),
        "opportunities",
        "type in ('PUBLIC_INSTITUTION_JOB', 'STATE_OWNED_ENTERPRISE_JOB', "
        "'CIVIL_SERVICE', 'GRASSROOTS_PROGRAM', 'YOUTH_POLICY_BENEFIT', "
        "'POSTGRAD_RECOMMENDATION', 'ADMISSION_CHANGE')",
    )
    op.drop_constraint(op.f("ck_evidence_refs_locator_schema_form"), "evidence_refs", type_="check")
    op.drop_constraint(
        op.f("ck_evidence_refs_locator_payload_shape"), "evidence_refs", type_="check"
    )
    op.drop_constraint(
        op.f("ck_evidence_refs_full_document_locator_value"),
        "evidence_refs",
        type_="check",
    )
    op.drop_constraint(
        op.f("ck_evidence_refs_locator_kind_values"),
        "evidence_refs",
        type_="check",
    )
    op.alter_column("evidence_refs", "locator_value", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("evidence_refs", "locator_payload")
    op.drop_column("evidence_refs", "locator_schema_version")
    op.create_check_constraint(
        op.f("ck_evidence_refs_locator_kind_values"),
        "evidence_refs",
        "locator_kind in ('page', 'paragraph', 'css_selector', 'text_span', 'full_document')",
    )
    op.create_check_constraint(
        op.f("ck_evidence_refs_full_document_locator_value"),
        "evidence_refs",
        "locator_kind <> 'full_document' or locator_value = '*'",
    )
    op.drop_constraint(op.f("uq_raw_artifacts_artifact_id"), "raw_artifacts", type_="unique")
    # ### end Alembic commands ###
